version: '3.5'

services:
  frontend:
    image: mlfrontend
    ports:
      - 3000:3000

  backend:
    image: mlbackend
    ports:
      - 5000:5000
    volumes:
      - training:/src/model

  training:
    image: mltraining
    volumes:
      - training:/src/model
      - images:/src/imgs

volumes:
  training:
  images: