version: '3.5'

services:
  backend:
    image: hellobackend:1.14
    ports:
      - 3000:8080
    environment:
      - REDIS_HOST=redis_cont
      - POSTGRES_HOST=postgres_cont
    depends_on:
      - "redis"
      - "postgres"

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis_cont
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres_cont
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  frontend:
    image: hellofrontend:1.14
    ports:
      - 5000:5000